#ifndef _ERROR_H_
#define _ERROR_H_

#define FILE_NOT_FIND 1
#define HAVE_LOOP 1
#define MULTI_FILE_PATH 1
#define PARAMETER_NOT_EXISTS 2
#define NO_FILE_PATH 3
#define FILE_PATH_FORM_ERROR 4
#define NO_CHAR 5
#define CHAR_FORM_ERROR 6
#define PARAMETER_FORM_ERROR 7
#define ALLOC_MEMORY_ERROR 8
#define PATH_NOT_EXISTS 9

#endif